// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnpLHK5btlp1G0PaL38F2mlsRJnDol8nQ',
    appId: '1:532704255237:web:3a4dd56879b752e79beb6c',
    messagingSenderId: '532704255237',
    projectId: 'test-4c8b8',
    authDomain: 'test-4c8b8.firebaseapp.com',
    storageBucket: 'test-4c8b8.appspot.com',
    measurementId: 'G-8FHE7FK2Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLgDnMFHlixEIb4Ni127P_lIT3ftR9X8k',
    appId: '1:532704255237:android:987d76a78e59e55c9beb6c',
    messagingSenderId: '532704255237',
    projectId: 'test-4c8b8',
    storageBucket: 'test-4c8b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJBcfgUaK_YYtrSKkLqR8xL-EjbHNrtcs',
    appId: '1:532704255237:ios:d7c0bf45bbd7d7909beb6c',
    messagingSenderId: '532704255237',
    projectId: 'test-4c8b8',
    storageBucket: 'test-4c8b8.appspot.com',
    iosClientId: '532704255237-sgcdc4q3g537homkn3j66tmdvbk3tv5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJBcfgUaK_YYtrSKkLqR8xL-EjbHNrtcs',
    appId: '1:532704255237:ios:81100bd0280a62af9beb6c',
    messagingSenderId: '532704255237',
    projectId: 'test-4c8b8',
    storageBucket: 'test-4c8b8.appspot.com',
    iosClientId: '532704255237-da3i2i1a2b493b55sapj8uhfcdccasui.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping.RunnerTests',
  );
}
